# Generated by Django 2.1.7 on 2019-07-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauriciopires', '0002_auto_20190722_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='checkin',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='images',
            name='checkout',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='info',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='images',
            name='pictures',
            field=models.CharField(max_length=5),
        ),
    ]
