# Generated by Django 2.1.7 on 2019-07-26 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mauriciopires', '0004_auto_20190725_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mauriciopires.Photographers'),
        ),
    ]
