# Generated by Django 2.1.7 on 2019-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauriciopires', '0007_auto_20190725_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='deadline',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='app',
            field=models.CharField(choices=[('PS', 'PhotoShop'), ('LR', 'LightRoom')], max_length=50),
        ),
    ]
