# Generated by Django 2.1.7 on 2019-10-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauriciopires', '0011_auto_20191005_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pictures',
            field=models.IntegerField(),
        ),
    ]
