# Generated by Django 3.0.6 on 2020-05-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauriciopires', '0014_auto_20200523_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='client',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
