# Generated by Django 3.0.6 on 2020-06-02 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mauriciopires', '0015_images_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='checkin',
        ),
    ]
